neet/masto.js

src/client/EventHandler.ts
src/client/Mastodon.ts
src/client/options.ts
src/entities/Conversation.ts

This PR is including the supports of upcoming the new version of Mastodon. Conversation API and `min_id` support of pagination.
- tootsuite/mastodon#8832
- tootsuite/mastodon#8736

Mastodon 2.6.0: Conversation API and min_id support

---

src/client/Mastodon.ts

Worth noting you *should* be able to set the version type to a literal constraint as you've done, but it seems there's a bug in current TypeScript preventing it.

Sets search API version properly; uses GET instead. Fixes #26.

---

src/client/Mastodon.ts
src/client/options.ts
src/entities/AccessToken.ts
src/entities/Account.ts

WIP: Support Mastodon 2.7.0

---

src/client/__tests__/gateway.spec.ts
src/client/__tests__/masto-events.spec.ts
src/client/gateway.ts
src/client/masto-events.ts

- Use `Sec-Websocket-Protocol` to pass token instead of querystring (tootsuite/mastodon#10818)

Support Mastodon 2.8.4

---

src/client/masto.ts

Hi there! `createStatus` was returning a `Promise<{}>` when called, which made it difficult to use the result. This PR fixes that issue.
`masto.d.ts` before this PR:
```ts
createStatus(params?: CreateStatusParams, idempotencyKey?: string): Promise<{}>;
```
`masto.d.ts` after this PR:
```ts
createStatus(params?: CreateStatusParams, idempotencyKey?: string): Promise<Status>;
```

fix return type of createStatus

---

src/client/params.ts

Fix typo of `FetchAccessTokenParamsWithPassword`

---

src/client/masto.ts
src/client/params.ts

- Add `account_id` param to `fetchNotification` tootsuite/mastodon#10796
- Change return type of `removeStatus` to `Status` tootsuite/mastodon#10669

Add supports of Mastodon 2.9.1 RC1

---

src/clients/masto/__tests__/__snapshots__/masto.spec.ts.snap
src/clients/masto/__tests__/masto.spec.ts
src/clients/masto/masto.ts
src/clients/masto/params.ts
src/entities/instance.ts

Support Mastodon 3.1.4

---

.eslintrc.json
examples/create-new-status-with-image.ts
src/clients/masto/__tests__/__snapshots__/masto.spec.ts.snap
src/clients/masto/__tests__/masto.spec.ts
src/clients/masto/masto.ts
src/entities/attachment.ts
src/utils/delay.ts

Partly resolves, #303 
This PR makes `Attachment.url` optional but it should've been optional since v3. thus I will not bump the major version.

Add Masto#fetchMediaAttachment and Masto#waitForMediaAttachment

---

src/clients/masto/masto.ts
src/gateway/decorators.ts
src/gateway/gateway-impl.ts

I'm getting the following error when running masto.js on mastodon.social:
```
Invalid Version: 3.3.0rc1
TypeError: Invalid Version: 3.3.0rc1
at new SemVer (node_modules/semver/classes/semver.js:41:13)
at compare (node_modules/semver/functions/compare.js:3:3)
at Object.lt (node_modules/semver/functions/lt.js:2:29)
at Masto.descriptor.value [as createMediaAttachment] (node_modules/masto/dist/index.js:881:69)
at doToot (src/main.ts:138:30)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
It looks like the version of Mastodon running on mastodon.social is `3.3.0rc1`, which isn't a valid semver string (the valid version of this would be `3.3.0-rc1`, with a hyphen). We can verify this in the node repl:
```
> const semver = require('semver')
> semver.valid('3.3.0rc1')
null …
```

Fix semver throwing on mastodon.social

---

README.md

All of available methods are described in the [documentation] points to a dead page. Updated link to go to correct documentation page.

Fix "documentation" hyperlink

---

src/entities/index.ts
src/entities/instance.ts
src/entities/link.ts
src/entities/status-edit.ts
src/entities/status-source.ts
src/entities/token.ts
src/paginator.ts
src/repositories/account-repository.ts
src/repositories/notification-repository.ts
src/repositories/report-repository.ts
src/repositories/status-repository.ts
src/repositories/trend-repository.ts
src/ws/ws.ts

https://github.com/mastodon/mastodon/releases/tag/v3.5.0rc1

Mastodon 3.5.0

---

src/http/base-http.ts
src/http/http-axios-impl.ts
src/http/http-native-impl.ts

Previously, `request()` method from `HttpAxiosImpl` & `HttpNativeImpl` sometimes threw an error like below:
Uncaught (in promise) Error: Unknown content type application/json; charset=utf-8, {...}
It happened when a response from server contains `Content-Type` header with some parameters, e.g., `application/json; charset=utf-8`.
It might be better to make `deserialize()` method from `SerializerNodejsImpl` & `SerializerNativeImpl` to trim parameters from their input, but I trim parameters from response content types instead.  If you leave a comment on this I'm going to address that.
Also there's one more fix on `HttpNativeImpl.request<T>()` method.  It should return `Response<T>`, but actually returned `T` instead.  I addressed this bug as well.
The standard `fetch()` API automatically …

Fix several bugs on `HttpNativeImpl`

---

src/http/http-native-impl.ts

An older version of masto.js worked pretty fine with React Native, but this compatibility broke recently.
Reverting the way how headers are mapped fixes the issue.

revert to reading headers for React Native compatibility

---

src/entities/account.ts

The [Account#suspended](https://docs.joinmastodon.org/entities/account/#suspended) property was missing, I've added it to the type. I tested it and it works.

add suspended flag to account

---

src/paginator.ts

fix: Use `params` instead of `data` in pagination

---

src/http/http-axios-impl.ts
yarn.lock

Actually send user-specified headers in `HttpAxiosImpl`

---

src/repositories/account-repository.ts

This PR fixes an incorrect call to get following accounts of an account

fix: Correct iterable used when fetching following accounts

---

examples/timeline-with-iterable.ts
src/repositories/account-repository.ts
src/repositories/block-repository.ts
src/repositories/bookmark-repository.ts
src/repositories/conversation-repository.ts
src/repositories/domain-block-repository.ts
src/repositories/endorsement-repository.ts
src/repositories/favourite-repository.ts
src/repositories/follow-request-repository.ts
src/repositories/followed-tag-repository.ts
src/repositories/iterable-repository.ts
src/repositories/list-repository.ts
src/repositories/mutes-repository.ts
src/repositories/notification-repository.ts
src/repositories/repository.ts
src/repositories/scheduled-statuses-repository.ts
src/repositories/timelines-repository.ts
src/repositories/trend-repository.ts
tests/accounts.spec.ts

Currently, the repository classes provide a method named `getXXXIterable` that returns a `Paginator` instance, but the name is unintuitive and too long.
This PR renames `getXXXIterable` to `iterateXXX` to solve this problem

chore: Rename getXXXIterable to iterateXXX

---

src/entities/instance.ts

The typing for the poll configuration was just copy-pasted from the media attachment settings. So I fixed that, and it was missing the account configuration.
That's all for now. If we want to update to the `v2` API there are other new configuration fields available.

Fix wrong types on fetch instance information

---

src/repositories/account-repository.ts

Adds `excludeReblogs` and `tagged` options to `masto.accounts.iterateStatuses`. These were added to the API in 2.7.0 and 2.8.0 respectively.

Additional account status options

---

fetch.d.ts
package.json

This allows users who aren't yet on Node16 resolution to have type support when importing from `masto/fetch`.

chore: add backwards-compatible type declarations

---

src/http/base-http.ts
src/http/http.ts
src/paginator.spec.ts
src/paginator.ts

When you invoke fetch version `masto.accounts.updateCredentials` in CORS aware environment, you'll get an error because   the HTTP method `patch` mismatches with the allowed HTTP method `PATCH`.
This is because other methods including `GET` , `POST`, `DELETE`, and `PUT` are specified to be normalized to case-insensitive, so CORS check passes regardless of the case. However, PATCH is not listed are the method to normalize.
More info: https://github.com/github/fetch/issues/37

fix: Change HTTP methods to uppercase

---

src/paginator.ts

Calling `next` method will mutate the paginator, so I want to avoid this. Then cloning the paginator is necessary.

feat: add clone for Paginator

---

src/paginator.ts

As returned here, `value` is always `undefined`.
https://github.com/neet/masto.js/blob/fbfd515ee3ef09e7050868d0d886993f0c93e611/src/paginator.ts#L21
So I add the `undefined` param into `IteratorResult`, otherwise, the default value is any. It'll break strict type.

fix: add value type of done result

---

src/http/http-native-impl.ts

Resolve #833
Remove `Content-type` header when it is set to be `application/json` and the body is undefined.

fix: Remove JSON content type when body is empty

---

src/mastodon/v1/entities/index.ts
src/mastodon/v1/entities/translation.ts
src/mastodon/v1/repositories/status-repository.ts

Resolve #856 
This PR adds `/translate` API that allows you to translate a status to another language was introduced at 4.0.0. You can use it as follows.
```ts
import { login } from "masto";
const masto = await login(...);
const statuses = await masto.v1.timelines.listPublic({ local: true }).next();
const status = statuses.value[0];
console.info(`Status: ${status.content}`);
const translation1 = await masto.v1.statuses.translate(status.id, { lang: 'ja' });
console.info(`Translation: ${translation.content}`);
```

feat: Add translate API

---

src/mastodon/v2/repositories/filter-repository.ts

The mastodon documentation does not reflect reality, [a pull request](https://github.com/mastodon/documentation/pull/1177) has been opened to fix it in the docs. The pull request, while approved, has not yet been merged.

fix: wholeWord is a boolean, not a string

---

src/paginator.spec.ts
src/paginator.ts

This used to rely on the link header having first the next and then the prev link.
Trying to track down why pagination in Elk with [Takahe](https://github.com/jointakahe/takahe) is broken even though it is supposed to be Mastodon API compatible. Don't think this will get it working immediately, but found this issue when trying out pagination with masto.js directly.

fix: Link header parsing when order is first prev and then next link

---

src/mastodon/v1/entities/instance.ts

`charactersReservedPerUrl` should be number type.
API Doc: https://docs.joinmastodon.org/entities/V1_Instance/#characters_reserved_per_url

Fix type error in V1::instance

---

src/mastodon/rest/v1/account-repository.ts
tests/rest/v1/accounts.spec.ts

Hello, this PR adds a `duration` parameter support for the account mute method. The `duration` parameter was added in v3.3.0, which takes the number of seconds to mute, instead of muting the account forever.
ref. accounts API methods - Mastodon documentation - https://docs.joinmastodon.org/methods/accounts/#mute
By the way, with this parameter support, Elk could have a feature to allow users to apply shorter muting (https://github.com/elk-zone/elk/issues/2301).

feat: Support duration parameter for account muting

---

package.json

Add new items into keyword list for relevant search terms. Currently it's impossible to find the package by queries like:
* "activitypub client"
* "fediverse client"
In the same time other packages could be found. To solve this I've added the next keywords:
* client
* activitypub
* federated
* fediverse

Add new keywords to package.json

---

src/mastodon/rest/v1/account-repository.ts
src/mastodon/rest/v1/media-attachment-repository.ts
src/mastodon/rest/v1/status-repository.ts
src/mastodon/rest/v2/media-attachment-repository.ts

Fix for https://github.com/neet/masto.js/discussions/977

fix: Use `Blob | string` as a type annotation for media

---

src/mastodon/entities/v2/search.ts

fix: Fix type of hashtags to be an array in `Search` entity

---

src/adapters/action/dispatcher-http-hook-mastodon.ts
src/adapters/action/dispatcher-http.ts
src/adapters/http/base-http.ts
src/interfaces/action.ts

fix: Use PUT for update for Mastodon-fork compatibility

---

src/mastodon/oauth/token-repository.ts
test-utils/jest-global-setup.ts
test-utils/pools/token-factory-docker.ts
tests/oauth/token.spec.ts

feat: Support `grant_type: authorization_code` and `client_credentials`.

---

.eslintrc.json
src/mastodon/entities/v1/account.ts
src/mastodon/entities/v1/admin/cohort.ts
src/mastodon/entities/v1/admin/dimension.ts
src/mastodon/entities/v1/admin/domain-block.ts
src/mastodon/entities/v1/admin/email-domain-block.ts
src/mastodon/entities/v1/admin/ip-block.ts
src/mastodon/entities/v1/admin/measure.ts
src/mastodon/entities/v1/admin/report.ts
src/mastodon/entities/v1/admin/tag.ts
src/mastodon/entities/v1/announcement.ts
src/mastodon/entities/v1/filter.ts
src/mastodon/entities/v1/instance.ts
src/mastodon/entities/v1/list.ts
src/mastodon/entities/v1/marker.ts
src/mastodon/entities/v1/media-attachment.ts
src/mastodon/entities/v1/notification.ts
src/mastodon/entities/v1/poll.ts
src/mastodon/entities/v1/preference.ts
src/mastodon/entities/v1/preview-card.ts
src/mastodon/entities/v1/report.ts
src/mastodon/entities/v1/scheduled-status.ts
src/mastodon/entities/v1/status.ts
src/mastodon/entities/v1/suggestion.ts
src/mastodon/entities/v1/tag.ts
src/mastodon/entities/v1/web-push-subscription.ts
src/mastodon/entities/v2/filter.ts
src/mastodon/entities/v2/instance.ts

Currently, we are offering type definitions for response types that are not associated to any REST API resource that are defined in docs.joinmastodon.org, such as `AccountField` or `NotificationType`. 
However, this implementation has several problems:
1. Since it is not a officially defined terminology of the REST API, it is likely to cause a conflict or breaking change once Mastodon started to offer a REST API resource that has the same name.
2. For types that consists of multiple words (such as `AdminReportNotification`), it is quite ambiguous to determine which naming convention it follows.
To resolve this, I'm changing these types to use `namespace`, allowing us to define non-resource types locally within REST resources.
You may think that TypeScript `namespace` is deprecated, but it …

chore(refactor): Use namespaces for Mastodon entities

---

src/adapters/config/http-config.spec.ts
src/adapters/config/http-config.ts

This pull request changes the behaviour for `timeout: undefined` to fall back to the default timeout milliseconds of Fetch API instead of using `300 * 1000 ms`.
I don't regard this as a breaking change, as the default timeout of the Fetch API depends on the runtime.
Partially closes #1097

fix: Change `timeout: undefined` to fall back to Fetch API default timeout

---

src/mastodon/entities/v1/preview-card.ts

Hello, I'm currently implementing a new author information feature in Elk (https://github.com/elk-zone/elk/issues/2995) but I noticed that masto.js doesn't have new fields for that.
This PR adds new fields `accounts` and deprecates two fields `account_name` and `account_url` following the updated documentation.
Here's the Mastodon documentation page for the new `authors` field: https://docs.joinmastodon.org/entities/PreviewCard/#authors

feat: Support new `accounts` field in `PreviewCard` of status introduced by Mastodon 4.3.0

---

src/adapters/ws/web-socket-connector.spec.ts
src/adapters/ws/web-socket-connector.ts

fix: Unset `ws` of WebSocketConnectorImpl after close event

---

src/adapters/clients.ts
src/adapters/config/web-socket-config.spec.ts
src/adapters/config/web-socket-config.ts
src/interfaces/config/web-socket-config.ts

fix: Use Authorization header for sending access_token to WebSocket API

---

src/mastodon/entities/v1/notification.ts
src/mastodon/entities/v1/relationship-severance-event.ts

Hello, this PR fixes two type definitions, found when implementing the support for relationship severance notification on Elk.
1. When the notification type is `severed_relationships` the correct prop name was actually `event`.
- Mastodon documentation: https://docs.joinmastodon.org/entities/Notification/#relationship_severance_event
- Source code: https://github.com/mastodon/mastodon/blob/main/app/serializers/rest/notification_serializer.rb#L12
- It seems that `key: :event` specifies the JSON key name for `relationship_severance_event` value here.
- ref. rails-api/active_model_serializers - https://github.com/rails-api/active_model_serializers/blob/v0.10.6/docs/general/serializers.md#attribute
2. Properties of `RelationshipSeveranceEvent`
The initial `relationships_count` was split into …

fix: update type information related to relationship severance

---

src/adapters/clients.ts
src/adapters/config/web-socket-config.spec.ts
src/adapters/config/web-socket-config.ts
src/interfaces/config/web-socket-config.ts

Revert #1255 as custom header is not supported in web browsers

fix: Revert "fix: Use Authorization header for sending access_token to WebSocket API"
