src/entities/Status.ts

Closes #24 
- tootsuite/mastodon#9120

Add `card` key to Status entity

---

src/client/EventHandler.ts

Change EventHandler to try to parse everything

---

src/client/options.ts

Fix context key of UpdateFilter

---

src/client/__tests__/__snapshots__/masto.spec.ts.snap
src/client/__tests__/masto.spec.ts
src/client/masto.ts
src/entities/account.ts

Ref: https://github.com/tootsuite/mastodon/pull/10297
Closes #53

Support Identity proofs

---

src/entities/filter.ts

Fix filter['id'] type

---

src/entities/instance.ts

Add `short_description` & `approval_required`

---

package.json
rollup.config.js
src/gateway/__tests__/websocket.spec.ts
src/gateway/gateway.ts
src/gateway/websocket.ts
tsconfig.json
yarn.lock

Support ESM

---

src/clients/masto/__tests__/masto.spec.ts
src/clients/masto/masto.ts

Make fetchNotification paginatable

---

src/gateway/__tests__/create-form-data.spec.ts
src/gateway/create-form-data.ts

Fix transformer for multipart/form-data

---

src/clients/masto/params.ts

ref tootsuite/mastodon/pull/11977

Add `exclude_unreviewed` to search

---

src/clients/masto/params.ts

Add `reason` param to CreateAccountParams

---

src/clients/masto/__tests__/__snapshots__/masto.spec.ts.snap
src/clients/masto/__tests__/masto.spec.ts
src/clients/masto/masto.ts

Resolves #169 
This PR also fixes a typo "dissmiss" to "dismiss"

Fix URL of dismissNotification

---

package.json
rollup.config.js
yarn.lock

Use @rollup

---

src/clients/masto/__tests__/__snapshots__/masto.spec.ts.snap
src/clients/masto/__tests__/masto.spec.ts
src/clients/masto/masto.ts
src/clients/masto/params.ts
src/entities/attachment.ts
src/entities/card.ts
src/entities/relationship.ts

Support Mastodon 3.2.0

---

src/clients/masto/__tests__/__snapshots__/masto.spec.ts.snap
src/clients/masto/__tests__/masto.spec.ts
src/clients/masto/masto.ts
src/entities/account-featured-tags.ts
src/entities/index.ts

- feat: Add `/accounts/:id/featured_tags` tootsuite/mastodon#11817

Support Mastodon 3.3.0

---

src/serializers/serializer-impl.spec.ts
src/serializers/transform-keys.ts

fix: Transform arrays inside an object

---

src/clients/masto.ts
src/http/index.ts

fix: Remove mock exports

---

.vscode/settings.json
src/entities/instance.ts

- Add instance#configuration mastodon/mastodon#16485

Support Mastodon 3.4.2

---

examples/create-new-status-with-image.ts
examples/create-new-status.ts
examples/moderate-reports.ts
examples/object-oriented.ts
examples/register-new-app.ts
examples/timeline-rxjs.ts
examples/timeline-with-iterable.ts
examples/timeline-with-streaming.ts
examples/update-profile.ts

fix: Fix unhandled promise rejection of examples

---

src/entrypoints/nodejs.ts

fix: Remove obsolete debug code

---

src/http/base-http.ts
src/http/http-axios-impl.ts
src/serializers/rails-querystring.spec.ts
src/serializers/rails-querystring.ts
src/ws/base-ws.ts

fix: Use Rails formed URL search params

---

src/http/base-http.ts
src/http/http-axios-impl.ts
src/serializers/serializer-native-impl.ts
src/serializers/serializer-nodejs-impl.ts
src/serializers/serializer.ts
tests/accounts.spec.ts

Close #689 
URL search params had not been transformed by serializer since v4.6.0

fix: Transform of URL search params' cases

---

package.json
yarn.lock

fix: Force to use Axios 1.1.3

---

src/serializers/rails-querystring.spec.ts
src/serializers/rails-querystring.ts

fix: Encode URI components in serializer

---

src/paginator.ts
src/repositories/repository.ts

Pagination params fix

---

src/entities/status.ts

https://docs.joinmastodon.org/entities/Status/#edited_at

Add Status editedAt

---

src/entities/notification.ts

https://docs.joinmastodon.org/entities/Notification/#type

Update Notification.type types

---

src/clients/masto.ts
src/entities/tag.ts
src/repositories/followed-tag-repository.ts
src/repositories/index.ts
src/repositories/tag-repository.ts
tests/followed-tags.spec.ts

feat: Support tag follow / unfollow

---

src/serializers/rails-querystring.ts

!isObject(object) includes `== undefined`

refactor: tidy up rails-querystring

---

README.md

chore(docs): Add note about Mastodon-compatible softwares

---

src/entities/filter.ts

fixes #725 to update the Filter interface

Fix the type of Filter.wholeWorld to boolean

---

src/ws/ws-native-impl.ts

fix: Remove JSON.parse for delete event type

---

src/http/http-native-impl.ts

fix: Change Content-Type to undefined when body is a FormData

---

src/mastodon/v1/entities/account.ts

docs: https://docs.joinmastodon.org/entities/Account/#moved

fix: update `moved` field type of Account

---

src/login.ts

masto.js will request instance data internally, and it's good to expose it to avoid requesting it again on userland.

feat: create client from known instance

---

src/mastodon/v1/entities/relationship.ts
src/mastodon/v1/repositories/account-repository.ts

I reordered fields (sync with official doc) and added missing fields.

fix: add missing fields for entity

---

README.md

chore: Add a link to the migration guide v5

---

src/mastodon/v1/entities/preference.ts
src/mastodon/v1/repositories/account-repository.ts

Support Mastodon 4.1.0

---

src/mastodon/v1/entities/list.ts

fix: Add missing repliesPolicy to List

---

src/mastodon/v2/aggregate-repository.ts

fix: Correct version range of /api/v2/search

---

src/login.ts

fix: Fix `disableVersionCheck` being ignored

---

tests/v2/filters.spec.ts

chore(test): Add test for _destroy parameter for filters.update

---

src/mastodon/v1/entities/filter-keyword.ts

We'd missed this one on my previous PR

fix: wholeWord is a boolean

---

src/adapters/action/dispatcher-http.ts
src/adapters/action/proxy.spec.ts
src/adapters/action/proxy.ts
tests/rest/v1/timelines.spec.ts

fix: Handle camelCase selection in proxy as an exception

---

src/mastodon/oauth/client.ts
tests/oauth/token.spec.ts

feat: Add token.revoke to OAuth client

---

src/mastodon/rest/v1/search-repository.ts
src/mastodon/rest/v2/search-repository.ts
tests/rest/v2/search.spec.ts

fix: Fix search API to return paginator

---

.github/workflows/ci.yml
package.json
src/adapters/action/dispatcher-http-hook-mastodon.spec.ts
src/adapters/action/dispatcher-http-hook-mastodon.ts
src/adapters/action/dispatcher-http.ts
src/adapters/action/dispatcher-ws.spec.ts
src/adapters/action/dispatcher-ws.ts
src/adapters/action/proxy.spec.ts
src/adapters/action/proxy.ts
src/adapters/clients.ts
src/interfaces/action.ts

chore(refactor): Refactor HTTP dispatcher

---

CHANGELOG.md
package-lock.json
package.json

Revert "chore(main): release 6.7.3"

---

src/mastodon/entities/v1/preview-card.ts

fix: Add missing `language` attribute to PreviewCard type

---

src/mastodon/rest/v1/app-repository.ts

fix: Allow multiple URIs in redirectUris in POST /v1/app

---

src/adapters/serializers/flatten.spec.ts
src/adapters/serializers/flatten.ts
src/adapters/serializers/serializer-native-impl.spec.ts

fix: Fix URL Search Parameter with falsy value gets omitted

---

src/mastodon/entities/v1/account-warning.ts
src/mastodon/entities/v1/admin/cohort.ts
src/mastodon/entities/v1/admin/dimension.ts
src/mastodon/entities/v1/admin/domain-block.ts
src/mastodon/entities/v1/admin/ip-block.ts
src/mastodon/entities/v1/admin/measure.ts
src/mastodon/entities/v1/appeal.ts
src/mastodon/entities/v1/domain-block.ts
src/mastodon/entities/v1/filter.ts
src/mastodon/entities/v1/grouped-notifications.ts
src/mastodon/entities/v1/index.ts
src/mastodon/entities/v1/list.ts
src/mastodon/entities/v1/marker.ts
src/mastodon/entities/v1/media-attachment.ts
src/mastodon/entities/v1/notification.ts
src/mastodon/entities/v1/preference.ts
src/mastodon/entities/v1/preview-card.ts
src/mastodon/entities/v1/relationship-severance-event.ts
src/mastodon/entities/v1/report.ts
src/mastodon/entities/v1/status.ts
src/mastodon/entities/v1/suggestion.ts
src/mastodon/entities/v1/web-push-subscription.ts
src/mastodon/entities/v2/filter.ts
src/mastodon/entities/v2/notification-policy.ts

feat: Support declaration merging in v1 and v2 entities

---

EXTENSIONS.md

chore: Add documentations for declaration merging
